-- Initial public schema for Warung Kopi POS on Supabase/Postgres
-- Source of truth adapted from:
-- lib/shared/database/app_database.dart
--
-- Design goals:
-- 1. Preserve current app behavior as closely as possible.
-- 2. Keep text-based IDs to simplify migration from SQLite.
-- 3. Keep enum-like values as TEXT because the Flutter app currently stores them as strings.
-- 4. Keep timestamp fields as TEXT in ISO8601 format to minimize migration friction.
--
-- If you later complete the Supabase migration, you can normalize:
-- - TEXT timestamps -> timestamptz
-- - INTEGER flags -> boolean
-- - TEXT enums -> PostgreSQL enum types

begin;

create table if not exists public.categories (
  id text primary key,
  name text not null,
  description text
);

create table if not exists public.products (
  id text primary key,
  category_id text not null,
  name text not null,
  sell_price double precision not null,
  cost_price double precision not null,
  stock_qty integer not null default 0,
  min_stock integer not null default 0,
  unit text not null,
  rack_location text,
  image_path text,
  is_active integer not null default 1,
  constraint products_is_active_check check (is_active in (0, 1)),
  constraint products_category_id_fkey
    foreign key (category_id)
    references public.categories (id)
    on delete restrict
);

create table if not exists public.app_profile (
  id text primary key,
  store_name text not null,
  store_subtitle text not null,
  owner_name text,
  photo_path text
);

create table if not exists public.customers (
  id text primary key,
  name text not null,
  phone text not null,
  address text not null,
  notes text,
  is_active integer not null default 1,
  created_at text not null,
  constraint customers_is_active_check check (is_active in (0, 1))
);

create table if not exists public.transactions (
  id text primary key,
  transaction_code text not null unique,
  customer_id text,
  customer_name text not null,
  total_amount double precision not null,
  payment_method text not null,
  amount_paid double precision not null default 0,
  change_amount double precision not null default 0,
  notes text,
  created_at text not null,
  constraint transactions_payment_method_check
    check (payment_method in ('cash', 'qris', 'transfer', 'card', 'bon')),
  constraint transactions_customer_id_fkey
    foreign key (customer_id)
    references public.customers (id)
    on delete set null
);

create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id text not null,
  product_id text not null,
  product_name text not null,
  quantity integer not null,
  sell_price double precision not null,
  constraint transaction_items_quantity_check check (quantity > 0),
  constraint transaction_items_transaction_id_fkey
    foreign key (transaction_id)
    references public.transactions (id)
    on delete cascade,
  constraint transaction_items_product_id_fkey
    foreign key (product_id)
    references public.products (id)
    on delete restrict
);

create table if not exists public.debts (
  id text primary key,
  transaction_id text not null unique,
  customer_id text not null,
  customer_name text not null,
  original_amount double precision not null,
  paid_amount double precision not null default 0,
  due_date text,
  notes text,
  created_at text not null,
  updated_at text not null,
  constraint debts_amount_check check (paid_amount >= 0 and original_amount >= 0),
  constraint debts_transaction_id_fkey
    foreign key (transaction_id)
    references public.transactions (id)
    on delete cascade,
  constraint debts_customer_id_fkey
    foreign key (customer_id)
    references public.customers (id)
    on delete restrict
);

create table if not exists public.debt_payments (
  id text primary key,
  debt_id text not null,
  customer_id text not null,
  amount double precision not null,
  payment_method text not null,
  notes text,
  paid_at text not null,
  constraint debt_payments_amount_check check (amount > 0),
  constraint debt_payments_payment_method_check
    check (payment_method in ('cash', 'qris', 'transfer', 'card', 'bon')),
  constraint debt_payments_debt_id_fkey
    foreign key (debt_id)
    references public.debts (id)
    on delete cascade,
  constraint debt_payments_customer_id_fkey
    foreign key (customer_id)
    references public.customers (id)
    on delete restrict
);

create table if not exists public.stock_movements (
  id text primary key,
  product_id text,
  reference_name text not null,
  quantity double precision not null,
  type text not null,
  notes text,
  created_at text not null,
  constraint stock_movements_type_check
    check (type in ('stockIn', 'stockOut')),
  constraint stock_movements_product_id_fkey
    foreign key (product_id)
    references public.products (id)
    on delete set null
);

create table if not exists public.operational_costs (
  id text primary key,
  month_year text not null,
  cost_name text not null,
  amount double precision not null
);

create index if not exists idx_transactions_created_at
  on public.transactions (created_at);

create index if not exists idx_transactions_customer_id
  on public.transactions (customer_id);

create index if not exists idx_transaction_items_transaction_id
  on public.transaction_items (transaction_id);

create index if not exists idx_debts_customer_id
  on public.debts (customer_id);

create index if not exists idx_debts_updated_at
  on public.debts (updated_at);

create index if not exists idx_debt_payments_debt_id
  on public.debt_payments (debt_id);

create index if not exists idx_stock_movements_product_created_at
  on public.stock_movements (product_id, created_at);

-- Seed minimum required row so the current app logic has a default profile.
insert into public.app_profile (
  id,
  store_name,
  store_subtitle,
  owner_name,
  photo_path
)
values (
  'store-main',
  'Warung Kopi Pertigaan Jati',
  'Pantau penjualan, stok, dan bon dalam satu aplikasi.',
  'Pemilik Toko',
  null
)
on conflict (id) do nothing;

-- Optional next step after auth is ready:
-- alter table public.categories enable row level security;
-- alter table public.products enable row level security;
-- alter table public.app_profile enable row level security;
-- alter table public.customers enable row level security;
-- alter table public.transactions enable row level security;
-- alter table public.transaction_items enable row level security;
-- alter table public.debts enable row level security;
-- alter table public.debt_payments enable row level security;
-- alter table public.stock_movements enable row level security;
-- alter table public.operational_costs enable row level security;

commit;
