begin;

alter table public.products
  add column if not exists is_ready integer not null default 1;

alter table public.products
  drop constraint if exists products_is_ready_check;

alter table public.products
  add constraint products_is_ready_check check (is_ready in (0, 1));

create table if not exists public.pending_transactions (
  id text primary key,
  customer_id text,
  customer_name text not null,
  total_amount double precision not null,
  notes text,
  created_at text not null,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  constraint pending_transactions_customer_id_fkey
    foreign key (customer_id)
    references public.customers (id)
    on delete set null
);

create table if not exists public.pending_transaction_items (
  id bigint generated by default as identity primary key,
  pending_transaction_id text not null,
  product_id text not null,
  product_name text not null,
  quantity integer not null,
  sell_price double precision not null,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  constraint pending_transaction_items_quantity_check check (quantity > 0),
  constraint pending_transaction_items_pending_id_fkey
    foreign key (pending_transaction_id)
    references public.pending_transactions (id)
    on delete cascade,
  constraint pending_transaction_items_product_id_fkey
    foreign key (product_id)
    references public.products (id)
    on delete restrict
);

create index if not exists idx_pending_transactions_owner_user_id
  on public.pending_transactions (owner_user_id);

create index if not exists idx_pending_transactions_created_at
  on public.pending_transactions (created_at);

create index if not exists idx_pending_transaction_items_owner_user_id
  on public.pending_transaction_items (owner_user_id);

create index if not exists idx_pending_transaction_items_pending_id
  on public.pending_transaction_items (pending_transaction_id);

alter table public.pending_transactions enable row level security;
alter table public.pending_transaction_items enable row level security;

drop policy if exists "pending_transactions_owner_all"
on public.pending_transactions;
create policy "pending_transactions_owner_all"
on public.pending_transactions
for all
using (owner_user_id = public.current_store_owner_user_id())
with check (owner_user_id = public.current_store_owner_user_id());

drop policy if exists "pending_transaction_items_owner_all"
on public.pending_transaction_items;
create policy "pending_transaction_items_owner_all"
on public.pending_transaction_items
for all
using (owner_user_id = public.current_store_owner_user_id())
with check (owner_user_id = public.current_store_owner_user_id());

commit;
